apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-app
  labels:
    app: retail
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retail
  template:
    metadata:
      labels:
        app: retail
    spec:
      containers:
      - name: retail
        image: sauraabh/retail-app:latest   # Change this
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
