name: CD Pipeline - Deploy to AKS

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Connect to AKS Cluster
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_AKS_CLUSTER_NAME }} \
            --overwrite-existing

      - name: Deploy to AKS
        run: |
          echo "Deploying application..."
          kubectl apply -f kubernetes/
          
          echo "Waiting for rollout..."
          kubectl rollout status deployment/retail-app --timeout=180s || echo "Rollout check done"

      - name: Show Status
        run: |
          kubectl get pods,svc
