name: Multi-Cloud Retail CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t sauraabh/retail-app:${{ github.sha }} ./app

      - name: Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'sauraabh/retail-app:${{ github.sha }}'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push sauraabh/retail-app:${{ github.sha }}
          docker tag sauraabh/retail-app:${{ github.sha }} sauraabh/retail-app:latest
          docker push sauraabh/retail-app:latest

      - name: Deploy to Azure AKS
        uses: azure/aks-set-context@v4
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: dev-retail-aks
          resource-group: dev-retail-rg
        continue-on-error: true

      - name: Deploy Application
        run: |
          kubectl apply -f kubernetes/
          kubectl set image deployment/retail-app retail=sauraabh/retail-app:${{ github.sha }} || true
