name: Multi-Cloud Retail CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t sauraabh/retail-app:${{ github.sha }} ./app

      - name: Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'sauraabh/retail-app:${{ github.sha }}'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push sauraabh/retail-app:${{ github.sha }}
          docker tag sauraabh/retail-app:${{ github.sha }} sauraabh/retail-app:latest
          docker push sauraabh/retail-app:latest
